### ISSUE TITLE
FR: introduce simplified (plain?, flat?) view (without tags hierarchy)

### ISSUE THREAD

**Issue by VKondakoff** [vrtmrz/obsidian-tagfolder#3] opened 2021-12-16 19:02 UTC
Hi!

I have noticed, that from time to time I miss a plain view without tag hierarchy (unless the tag nesting is specified explicitly: `#one/two/three`). Mainly the purpose is to reduce the tag clutter in the case there are limited number of tags.

So, if note has tags `#one` and `#two`, it will be displayed like this in tag folder tree:

```
> one
      note
> two
     note
```

and not like this:

```
> one
     > two
     note
> two
    > one
    note
```

May this be useful for somebody else? Is it difficult to implement?

Thanks!

**Comment by vrtmrz** [comment] 2021-12-16 22:52
Could this problem be solved by "Expand only n levels"?
It will not be so hard.
I will try to implement it.

**Comment by vrtmrz** [comment] 2021-12-17 03:36
@VKondakoff 

I implemented this as a limitation of expanding the trees.
Is this works for your usecase?

**Comment by VKondakoff** [comment] 2021-12-18 13:24
Yes, thanks, it works great for my usecase, because I'm not using nested tags.
In the current implementation nested tags are affected by new 'Level' system in the same way as plain tags. And if you choose `Level 1':
<img width="613" alt="Снимок экрана 2021-12-18 в 16 20 42" src="https://user-images.githubusercontent.com/230824/146642528-ac9ab748-8c52-4287-9c32-aaffe47a773b.png">

I strongly suggest to _exclude_ nested tags from the Level system, allowing them to be displayed nested independently of which Level is currently selected by user. So - Level system will work only with plain tags. What do you think?

**Comment by vrtmrz** [comment] 2021-12-18 16:18
Thank you!, but I'm using the nested tags in some cases
#dev #status/draft 
or
#citationneeded/when #citationneeded/who or some  same series
to pick and fix up uncompleted notes.

But your suggestions are so reasonable too.
I'm wondering which is a good way, 

1. Use the as same as other not dedicated tags
2. Do not expand the nested tag. Just keep as #status/draft.

**Comment by vrtmrz** [comment] 2021-12-28 05:39
I'm sorry I've misunderstood your idea.
You're right. Nested tags should be respected even the level system (Good name) is enabled.
I implemented this in version 0.6.0. Could you please check the behavior?

**Comment by VKondakoff** [comment] 2021-12-28 12:09
Yes, exactly! Thanks for writing back: version 0.6.0 works exactly how I expected. Bravo! 

There is one area to think about: should all the nested tags appear in the main tags list or not? For example I have the following tags: `#one/two/three #four #five`. With the current behaviour I see the following in the tags list:
```
> one
> four
> five
```
But maybe it should look like this?:
```
> one
> two
> three
> four 
> five
```

I'm not sure about this. This is just an idea for brainstorming. The interesting point is: how should TagFolder behave if I use the following nested tags: `#one/two/three` and `#six/two/three`? I think it may be interesting and useful if the notes will be displayed like this:
```
> one
   - here are the notes which have the tags #one (if any) and #one/two/three
> two
   - here are the notes which have the tags #two, #one/two/three and #six/two/three
> three
   - here are the notes which have the tags #three, #one/two/three and #six/two/three
> four
   - here are the notes which have the tags #four
> five 
   - here are the notes which have the tags #five
> six
   - here are the notes which have the tags #six/two/three

```
Your opinion?

BTW, TagFolder was just added to Obsidian Community Plugins. Congratulations, great work!

**Comment by V-U-Simon** [comment] 2022-01-20 14:00
I can suggest adding a button for the behavior as for folders.

In terms of implementation, I suggest using, for example, a regular expression: `/ \w*\/?]{0,}[\- \/]+YOUR_TAG$`
This will allow you to output only those tags that are at the current level
In case the tag was like a folder

```
> tag_folder
> tag_folder/tag_1
> tag_folder/tag_2
> tag_folder/tag_folder_inside_1/tag_3
> tag_folder/tag_folder_inside_1/tag_4
> tag_folder/tag_folder_inside_2/tag_5
```

now show is showing 
``` 
> tag_folder
    -> tag_folder_inside_1
            tag_3
            tag_4
    -> tag_folder_inside_2
            tag_5        
    tag_1
    tag_2
    tag_3
    tag_4
    tag_5
```

just need to show a last tag
``` 
> tag_folder
    -> tag_folder_inside_1
            tag_3
            tag_4
    -> tag_folder_inside_2
            tag_5        
    tag_1
    tag_2
```


P.S.
Can you write in the README your account details for transferring a some amount for coffee))

**Comment by phoopee3** [comment] 2022-01-23 16:49
@V-U-Simon Where can I implement that regex? I only want the notes to be shown at the matching level, not duplicated at the root and other levels.

**Comment by V-U-Simon** [comment] 2022-01-23 21:35
> @V-U-Simon Where can I implement that regex? I only want the notes to be shown at the matching level, not duplicated at the root and other levels.

Now you can implement this regex only on searching 

Look in attaching screenshot
![image](https://user-images.githubusercontent.com/51059106/150698804-772615cd-b2bd-4e35-8aed-1856a5821e39.jpeg) 


P.S. sorry for off-topic of this issue

**Comment by vrtmrz** [comment] 2022-01-24 05:29
Really sorry for being delayed.
I've been pondering this feature. And I think it shouldn't be avoided with workarounds.
I didn't know about Bear, It looks very similar but there is little a different thought between them. 
About to find a note, or to organize notes.
(TagFolder has been started for finding notes, but I think I want to make it more useful.)

```
> tag_folder
> tag_folder/tag_1
> tag_folder/tag_2
> tag_folder/tag_folder_inside_1/tag_3
> tag_folder/tag_folder_inside_1/tag_4
> tag_folder/tag_folder_inside_2/tag_5
```
This should be as like below.
![image](https://user-images.githubusercontent.com/45774780/150725072-51d99aa5-819c-4e7c-a089-66965267c085.png)

if you want this, it can be implemented:
![image](https://user-images.githubusercontent.com/45774780/150725370-0a594e8b-4b33-45ca-a1ba-07c451a12582.png)
(Photoshopped)

This should be a simple feature: "Do not expand items to intermediate level"

but If you want this:
![image](https://user-images.githubusercontent.com/45774780/150725483-bbd296e0-993b-4b6f-838f-d11834828ab0.png)

It should be harder... 

And one of the features: "Do not treat nested tags as dedicated levels" is available on v0.7.0.

**Comment by vrtmrz** [comment] 2022-01-25 04:01
> This should be a simple feature: "Do not expand items to intermediate level"

Implemented [this and more options](https://github.com/vrtmrz/obsidian-tagfolder#hide-items). 

Could you please try this?

**Comment by V-U-Simon** [comment] 2022-01-25 08:48
Thanks you!

During testing new version i found that some intermediates tags don't displayed

![Снимок экрана 2022-01-25 в 11 28 55](https://user-images.githubusercontent.com/51059106/150940358-da9a53c2-df8b-4aa4-9855-c9c83ee11dd7.png)

I think this problem is occurred from sequence tags writing or from quantity of tags
Everything ok if tag write like
```
---
tags:
- Language/SQL
date created: 2021-11-13 17:46
date updated: 2022-01-15 13:10
---
```

But don't displayed if it writing like
```
---
tags:
- Language/SQL
- Basic/operator
date created: 2021-12-16 11:42
date updated: 2022-01-10 12:47
---
```
or 
```
---
tags:
- Course
- Language/SQL
date created: 2021-11-13 17:49
date updated: 2021-11-13 17:57
---
```

**Comment by vrtmrz** [comment] 2022-01-25 09:06
@V-U-Simon Thank you for testing! 
But I didn't reproduce it.
May I ask `Expand limit` and `Hide items` settings?

**Comment by V-U-Simon** [comment] 2022-01-27 13:25
> @V-U-Simon Thank you for testing!
> But I didn't reproduce it.
> May I ask `Expand limit` and `Hide items` settings?

`Hide items` - 'only intermediates of nested tags'
I've tried any `Expand limit` but on the screenshot it's `level 1`

**Comment by vrtmrz** [comment] 2022-02-22 05:19
@V-U-Simon 
Thank you for the reproducing vault, I got the reason!
It has been fixed as "do not hide items that are in the levels deeper than limit"
Some limitation is there, (affects to nested tags too), but better than before.
Could you please try v0.9.1?

**Comment by V-U-Simon** [comment] 2022-02-22 08:31
OMG! Thanks man!
You are awesome

**Comment by tivervac** [comment] 2022-05-14 13:15
Hmmm, for me this doesn't appear to be working yet. I'm using version 0.10.0.

What I want is basically a file explorer, but using tags instead of folders. I'm already using the `Hide all intermediate` flag.

For example, in the picture below I would like to have something like

```
* art
  - Fore-edgepainting 
* books
  - Fore-edgepainting
* painting
  - Fore-edgepainting
```

That would make it possible to have files in different "folders" (tags that is) without making symlinks. It would also allow easy navigation

![afbeelding](https://user-images.githubusercontent.com/3389524/168427239-ca63d9e9-9025-4ece-8649-ac77f7952c1f.png)

**Closed** 2022-09-27 16:25 UTC
